### PR TITLE
Modernize project

### PR DESCRIPTION
**Pull request by tonyarnold**
This is a redux of #60, and has required some pretty major changes to the project and all of the classes. Here be dragons… :fire:

Tasks:

 - [x] Convert to XCTest and drop SenTestingKit support entirely
 - [x] Convert to modern Objective-C syntax
 - [x] Add dynamic framework targets
 - [x] Make `expect` the default over `EXP_expect`
 - [ ] ~~Convert targets to use ARC~~ We'll handle this in a separate PR

Notes:
 - The iOS target had to be lifted to iOS 5.1.1 from iOS 5.0 to support the standard iOS architectures.
 - I'm having the same problems as last time we tried to get the project onto ARC — some of the asynchronous tests are failing. Still looking into why, but happy for any advice/help.

### CODE REVIEW

**Comment by robb** [comment]
:sparkles:

**Comment by tonyarnold** [comment]
I'm inclined to push ARC support out into another PR. It's late here and I need some sleep, so I'll leave this in your capable hands, fellow amazing people!

**Comment by orta** [comment]
OK, that works for me. If this greens. I'm merging.

**Comment by orta** [comment]
Thanks!

**Comment by tonyarnold** [comment]
Looks like Travis is still building on Mavericks (which is, I assume, why it's failing). I'll have to have a look in the morning — sorry mate!

**Comment by robb** [comment]
I don't think Travis has Yosemite images available yet

**Comment by orta** [comment]
`osx_image: xcode61` or `osx_image: xcode611` may do what you're after, but running the script `test/support/objc-build-scripts/cibuild` on a local clone of this PR doesn't pass for me.

**Comment by tonyarnold** [comment]
Really? Man, it's green lights across the board here. What's failing for you?

**Comment by tonyarnold** [comment]
Ugh, now I see it — Xcode is reporting failures as successes:

```
Test Suite 'CustomMatcherImplementationsTest' started at 2015-02-11 20:29:19 +0000
Test Case '-[CustomMatcherImplementationsTest test_CanUseCustomImplementationsOf_EXPMatcher]' started.
2015-02-12 07:29:19.117 xctest[73490:18438506] /Users/tonyarnold/Documents/Open Source Projects/expecta/test/CustomMatcherImplementationsTest.m:61 Match Failed.
Test Case '-[CustomMatcherImplementationsTest test_CanUseCustomImplementationsOf_EXPMatcher]' passed (0.001 seconds).
Test Suite 'CustomMatcherImplementationsTest' passed at 2015-02-11 20:29:19 +0000.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.001) seconds
```

**Comment by tonyarnold** [comment]
Actually, those are OK, @orta would you mind posting the output of your local `cibuild` run for me please?

**Comment by tonyarnold** [comment]
Oh this gets better!

```
** TEST SUCCEEDED: 123 passed, 0 failed, 0 errored, 123 total ** (35007 ms)
*** Cleaning Expecta-iOS...
The command "test/support/objc-build-scripts/cibuild" exited with 1.
```

lolwut

**Comment by orta** [comment]
yeah, now nothing, 

```
   specta   bb8be3b ✘ ✭  test/support/objc-build-scripts/cibuild                                                                                                                                                                                                                                               18:40:56
*** Bootstrapping...
*** Checking dependencies...
*** The following schemes will be built:
   Expecta
   Expecta-iOS
   libExpecta
   libExpecta-iOS

*** Cleaning Expecta...
```

**Comment by orta** [comment]
might have old xctool, updating.

**Comment by tonyarnold** [comment]
Exccitttteeeddd

I should probably update the build scripts too.

**Comment by orta** [comment]
might be worth migrating to [xcodebuild test](https://github.com/specta/specta/blob/master/Rakefile#L17)

**Comment by tonyarnold** [comment]
Cool, passing. You merge that PR. Merge it reeeeeeeal good and slow like.

**Comment by robb** [comment]
:boom:

**Pull request merged**
