### PR TITLE
Project re-organisation, rakefile and documentation update

### PR DESCRIPTION
**Pull request by tonyarnold**
I'm rearranging things to look a bit more like a standard Xcode project. 

:hocho:

### CODE REVIEW

**Comment by tonyarnold** [comment]
Goddamnit, merge conflict.

**Comment by orta** [comment]
blame @chrismaddern's need for repo diversity

**Comment by tonyarnold** [comment]
OK, this is good to go if anyone wants to have a look. Miscellaneous cleanups that I thought it important to get out of the way.

**Comment by orta** [comment]
Maybe kill the `RDD.md` file?

**Comment by orta** [comment]
`Expecta.podspec` could do with changing line `19` to `  s.source_files = 'Expecta/**/*.{h,m}'`

**Comment by orta** [comment]
and adding `XCTest` to the [frameworks](https://github.com/specta/specta/blob/master/Specta.podspec#L13)

**Comment by tonyarnold** [comment]
Don't need to add XCTest (welcome to modules). The rest I agree with and will handle shortly.

**Comment by tonyarnold** [comment]
Oh right, for KerkerPerds

**Comment by orta** [comment]
Giphy

Merging on :green_heart:

**Comment by tonyarnold** [comment]
I :green_heart: that green, green status.

**Pull request merged**
