### PR TITLE
Upgrade for Xcode 10.1 (and Fix Warnings)

### PR DESCRIPTION
**Pull request by nsforge**
This PR:
- Upgrades the project for Xcode 10.1
- Adds all of the suggested compiler warnings suggested when when upgrading the project
- Fixes all outstanding compiler warnings
- Updates the iOS deployment target from 5.1.1 to 8.0 (since Xcode 10 only supports iOS 8.0+)

### CODE REVIEW

**Review by tonyarnold — CHANGES_REQUESTED** [review]
These changes look good to me, but the CI scripts are quite broken so we're not getting any automated testing of changes. Do you have any interest in fixing the build scripts, @nsforge?

**Comment by nsforge** [comment]
I'm having a quick look into the CI scripts now…

**Comment by nsforge** [comment]
@tonyarnold The CI fixes have been merged in, so this is ready for review again.

**Review by tonyarnold — APPROVED** [review]

**Review by tonyarnold — APPROVED** [review]

**Comment by tonyarnold** [comment]
Thanks for the contribution, @nsforge! Much appreciated!

**Pull request merged**
